[package]
name = "temporal_capi"
description = "C interface to temporal_rs"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
include = [
    "bindings/**/*",
    "src/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE-Apache",
    "LICENSE-MIT",
    "README.md"
]

[dependencies]
diplomat = "0.10.0"
diplomat-runtime = "0.10.0"
temporal_rs = { workspace = true, default-features = false }
icu_calendar = { version = "2.0.0-beta2", default-features = false }
