[package]
name = "temporal_capi"
description = "C interface to temporal_rs"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
include = [
    "bindings/**/*",
    "src/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE-Apache",
    "LICENSE-MIT",
    "README.md",
]

[dependencies]
diplomat = "0.12.0"
diplomat-runtime = "0.12.0"
num-traits.workspace = true
temporal_rs = { workspace = true, default-features = false }
timezone_provider = { workspace = true, default-features = false }
icu_calendar = { version = "2.0.2", default-features = false }
icu_locale = { version = "2.0.0" }
writeable = "0.6.1"
yoke = { version = "0.8.0", optional = true }
zoneinfo64 = { workspace = true, optional = true }

[features]
compiled_data = ["temporal_rs/compiled_data"]
zoneinfo64 = ["dep:zoneinfo64", "timezone_provider/zoneinfo64", "yoke"]

[package.metadata.docs.rs]
all-features = true
